#pragma once

namespace project_c
{
enum PrefabType
{
    PREFAB_TYPE_DEFAULT_CUBE,

    PREFAB_TYPE_BARBARIAN,

    PREFAB_TYPE_SKELETON_WARRIOR,


    PREFAB_TYPE_FLOOR,
    PREFAB_FLOOR_OUTSIDE_REGION,
    PREFAB_TYPE_WALL,
    PREFAB_TYPE_BOX,
    PREFAB_TYPE_COIN_GOLD,

    PREFAB_TYPE_COUNT
};

} // namespace project_c