#pragma once

namespace project_c
{
enum PrefabType
{
    PREFAB_TYPE_BARBARIAN,
    PREFAB_TYPE_SWORD,
    PREFAB_TYPE_DAGGER,
    PREFAB_TYPE_SKELETON_WARRIOR,
    PREFAB_TYPE_BARREL,
    PREFAB_TYPE_FLOOR,
    PREFAB_TYPE_FLOOR_DETAIL,
    PREFAB_TYPE_WALL,
    PREFAB_TYPE_CUBE,

    PREFAB_TYPE_COUNT
};

} // namespace project_c